import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import HeaderServer from "@/app/components/layouts/herder/HeaderServer";
import "./globals.css";

// Googleフォント「Geist Sans」と「Geist Mono」をNext.jsに読み込むための設定。
// それぞれフォント変数を設定して、latinサブセットを指定している。
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Next.jsのSEO用メタデータ。ページのタイトルと説明を定義している。
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// ルートレイアウトコンポーネント。全ページで共通して利用されるHTML構造を定義。
// Googleフォントのクラスや、全体の最小高さ・アンチエイリアス、flexレイアウトを設定。
//一番外側のレイアウト。
// MUI（Material UI）のAppRouterCacheProviderで全体をラップし、MUIのApp Router対応のキャッシュプロバイダーを提供。
// childrenには各ページのコンテンツが挿入される。
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AppRouterCacheProvider>
          {/* ヘッダー */}
          <HeaderServer /> 
          {/* 各ページのコンテンツをここで描画 */}
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
